M48
; DRILL file {KiCad 7.0.6} date Mon Aug 14 14:17:24 2023
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2023-08-14T14:17:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X16323Y-23398
X16323Y-24398
T2
X17126Y-21063
X17126Y-30118
X39961Y-21063
X39961Y-30118
T0
M30
